name: C

on:
  push:
    branches:
      -main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y valgrind time
    - name: Build
      run: make
    - name: Run tests
      run: make check
    - name: Run Valgrind (on tests)
      run: make memcheck
    - name: Run examples
      run: ./tests/run_examples.sh  
    - name: Run fib35 benchmark
      run: |
        echo "Time: "
        /usr/bin/time bin/monkey examples/fib35-recursive.monkey | tail -n1
